server:
  port: ${port:8888}

spring:
  application:
    name: config-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
#          uri: https://github:com/Bullishman/my_rental_config/blob/master/application.yml
          uri: file://${user.home}/MyRentalService/git-local-repo


management:
  endpoints:
    web:
      exposure:
        include: health, beans, httptrace, busrefresh